version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-3imu-lfwtd5o@sv8@phdo0i*zgkgy%_ifh=_9cboem5(8h6buy"
      - "DJANGO_DEBUG=True"

      - "EMAIL_USE_TLS=True"
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_HOST_USER=bloodpressuretracking@gmail.com"
      - "EMAIL_HOST_PASSWORD=a?3L83!qxCLozQ5E"
      
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"  

volumes:
  postgres_data: