version: '3.9'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=t9laBEwL3g2WEGCSoFIRj0wyD9_IYyvm1klg6ZHLbfURL6LJ1bo"

      - "EMAIL_USE_TLS=True"
      - "EMAIL_HOST=smtp.gmail.com"
      - "EMAIL_HOST_USER=bloodpressuretracking@gmail.com"
      - "EMAIL_HOST_PASSWORD=a?3L83!qxCLozQ5E"
      
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"  

volumes:
  postgres_data: